name: spectrace
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.*
  - scipy=1.13.*
  - pandas
  - matplotlib
  - librosa
  - h5py
  - pillow
  - openpyxl
  - scikit-learn
  - pytest
  - pip:
      - gimpformats