name: spectrace
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - matplotlib
  - librosa
  - h5py
  - pillow
  - openpyxl
  - scikit-learn
  - scipy
  - numpy
  - pytest
  - pip:
      - gimpformats