name: spectrace
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26
  - pandas
  - matplotlib
  - librosa
  - h5py
  - pillow
  - openpyxl
  - scikit-learn
  - scipy=1.14.1
  - pytest
  - pip:
      - gimpformats